### ISSUE TITLE
How to use `GoldenDict Select To Translate.ahk`?

### ISSUE THREAD

**Issue by escape0707** [escape0707/scripts#1]
> A:
> 我能问下goldendict这个脚本怎么用吗
> 
> A:
> [图片]
> 
> B:
> 行
> 
> B:
> 首先你要下载并安装autohotkey
> 
> B:
> 用choco就行
> 
> B:
> 其次，你要把我这个脚本下载下来（或者复制并保存成同样的扩展名
> 
> A:
> ok
> 
> B:
> 下载的话，右键另存为你截图的网页的‘raw’按钮就行
> 
> B:
> 两者都有以后，双击运行脚本即可
> 
> B:
> 需要暂停的话，就右键托盘区图标suspend
> 
> A:
>  这个raw指的是哪
> 
> A:
> [图片]
>

**Comment by escape0707** [comment]
这里：
![image](https://user-images.githubusercontent.com/11014745/75647979-a2cf7000-5c89-11ea-8fce-8aa678aed229.png)

**Comment by wuyuyu1024** [comment]
后缀用啥

**Comment by escape0707** [comment]
和文件名一样，`ahk`

**Comment by escape0707** [comment]
和文件名一样，`ahk`

**Comment by escape0707** [comment]
> 这个goldendict稍微有点不智能 可能是我没玩好   。 就是复数的时候他不会识别成那个词本身

设置里启用英文的 `morphology`

**Comment by wuyuyu1024** [comment]
复数或副词等特殊形式无法识别或本地词库没有的生僻词 能否解决

**Comment by escape0707** [comment]
> 
> 
> 复数或副词等特殊形式无法识别或本地词库没有的生僻词 能否解决

何夜无月:
在选词典的地方就有个叫做morphology的选项卡

何夜无月:
你去那里面启用一下english的

**Comment by escape0707** [comment]
> 
> 
> 复数或副词等特殊形式无法识别或本地词库没有的生僻词 能否解决

在选词典的地方就有个叫做morphology的选项卡
你去那里面启用一下english的

**Comment by escape0707** [comment]
Closed as the problem has already been solved for my friend.
