### ISSUE TITLE
adding Track Clipboard Changes to "GoldenDict Select To Translate"

### ISSUE THREAD

**Issue by hafeet685** [escape0707/scripts#2]
Hello Dear escape0707
I was seeking on the internet for a help for Goldendict and accidently got familiar to your amazing ahk script, actually is far best aide that I've test! THANK YOU!
I'm a student and an absolute beginner in programing. Could you do me a favor to provide a scrip of "GoldenDict Select To Translate" that track clipboard changes? I'm mean when something is copied, Goldendict popup appears.
Regards, hafeet

**Comment by escape0707** [comment]
Hi @hafeet685! Thanks for coming by and trying out my little work!

For the function you're interested in, I Googled "autohotkey clipboard change" and find that there is a function in autohotkey called OnClipboardChange that probably could help. 

https://www.autohotkey.com/docs/commands/OnClipboardChange.htm

I'm currently going to bed so I can only check that out tomorrow. If you are interested in it you can always give a shot on your own first. Just write a callback function to execute "goldendict %clipboardcontent%" and use the function in the document to register that callback then you are good.

Anyway, I'll update tomorrow. Feel free to ask!

**Comment by escape0707** [comment]
Just in case you don't know, <kbd>Ctrl</kbd>+<kbd>C</kbd>+<kbd>C</kbd> is a GoldenDict built-in hotkey to do a "copy and lookup" operation.

Anyway, the ahk you requested is this:

```autohotkey
; Translate clipboard text using GoldenDict on clipboard content change.

; Ignore attempts to launch when the script is already running
#SingleInstance Ignore


; Utility functions definitions: START
FindGoldenDictPath() {
    ; Find a installed GoldenDict
    PreviousRegView := A_RegView
    SetRegView, 32
    RegRead, FullFilePath, HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\GoldenDict, UninstallString
    SetRegView, %PreviousRegView%
    if (!ErrorLevel) {
        SplitPath, FullFilePath,, InstallPath
        Return, InstallPath . "\GoldenDict.exe"
    }

    ; If GoldenDict is not installed normally, check whether a scoop installed version exist
    ScoopFilePath := "C:\Users\" . A_UserName . "\scoop\apps\goldendict\current\GoldenDict.exe"
    if FileExist(ScoopFilePath) {
        Return, ScoopFilePath
    }

    Throw, "No GoldenDict installation could be found. You could still modify this .ahk file manually to provide a valid GoldenDictPath."
}


CloseGoldenDict() {
    Process, Close, GoldenDict.exe
}


; You can optionally comment out all following lines contains `ClipboardSave` to let the copied word remain in the clipboard
TranslateOnClipboardChange(Type) {
    if (A_IsSuspended) {
        return
    }
    
    global GoldenDictPath

    if (Type != 1) {
        return
    }
    Selected := Trim(Clipboard, " `t`r`n")
    SelectedLength := StrLen(Selected)
    if (SelectedLength <= 0 or SelectedLength > 50) {
        return
    }
    Selected := """" . Selected . """"
    Run, %GoldenDictPath% %Selected%
}
; Utility functions definitions: END


; Main Thread: START
GoldenDictPath := FindGoldenDictPath()
; Run GoldenDict if it's not running
Process, Exist, GoldenDict.exe
if (!ErrorLevel) {
    Run, %GoldenDictPath%
    ; Unfortunately, run options like Max|Min|Hide won't work for GoldenDict
}

; Register clean up function to be called on exit
OnExit("CloseGoldenDict")

; Register translate function on clipboard change
#Persistent
OnClipboardChange("TranslateOnClipboardChange")
```

**Comment by hafeet685** [comment]
Hi again dear @escape0707 
That is amazing! Thanks for your code and comments, actually I've dealt more with GoldenDict preferences and realized there is a such thing in config file located in "%APPDATA%\GoldenDict".
`<trackClipboardChanges>0</trackClipboardChanges>`
and If you change 0 to 1 and turn "Scan Popup" on, it will work!
By the way, the ahk you've written works great but I don't know why I can't suspend it.

**Comment by escape0707** [comment]
Good to know you've solved it on your own!

For the suspending feature, check this [stackoverflow answer](https://stackoverflow.com/a/18045654/5366367) for why.

**Comment by escape0707** [comment]
Btw, you need this `trackClipboardChanges` for looking up words in the subtitle inside a video player (like potplayer) or what? Just my curiosity through.

**Comment by hafeet685** [comment]
You nailed it! In Potplayer there is a feature when click on a word, It will copy to your clipboard.
By the way, the only thing that I understand from "stackoverflow" answer is that it's not easy to add suspending feature!
Thanks again for your coding and support. I almost use GoldenDict every day and I won't forget your great aide.

**Comment by escape0707** [comment]
That answer basically says that the callback function added by `OnClipboardChange` will always be invoked and does not respect the suspending or pausing status. So you have to add this check at the beginning of the callback function manually to achieve that:

```autohotkey
if (A_IsSuspended) {
    return
}
```

I've edited my code comment above so that you can check it out.
Good luck learning a foreign language!
